import React, { useEffect, useState } from 'react';
import { ArrowLeft, Loader2, TrendingUp, BarChart2, Calendar } from 'lucide-react';
import { collection, query, orderBy, getDocs } from 'firebase/firestore';
import { db } from '../lib/firebase';

interface AdminDashboardProps {
  onBack: () => void;
}

interface AnalyticsEntry {
  id: string;
  timestamp: number;
  analysis: string;
  entryCount: number;
}

export default function AdminDashboard({ onBack }: AdminDashboardProps) {
  const [entries, setEntries] = useState<AnalyticsEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    loadAnalytics();
  }, []);

  const loadAnalytics = async () => {
    try {
      const q = query(
        collection(db, 'global_analytics'),
        orderBy('timestamp', 'desc')
      );
      const snapshot = await getDocs(q);
      const data = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as AnalyticsEntry[];
      
      setEntries(data);
    } catch (err) {
      console.error("Failed to load analytics:", err);
      setError("Failed to load analytics data. Ensure you have the proper admin permissions.");
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (ts: number) => {
    return new Intl.DateTimeFormat('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit'
    }).format(new Date(ts));
  };

  return (
    <div className="flex flex-col h-screen bg-[#05070A] text-[#E0E6ED] font-sans relative overflow-hidden">
      <div className="absolute inset-0 atmosphere pointer-events-none"></div>
      
      {/* Header */}
      <header className="h-20 flex items-center justify-between px-6 lg:px-10 border-b border-white/5 flex-shrink-0 relative z-10 glass">
        <div className="flex items-center gap-4">
          <button
            onClick={onBack}
            className="text-white/40 hover:text-white/80 transition-colors p-2 -ml-2 rounded-xl hover:bg-white/5"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex items-center gap-4">
            <div className="w-8 h-8 rounded-full bg-violet-500/20 border border-violet-500/40 flex items-center justify-center">
              <TrendingUp className="w-4 h-4 text-violet-400" />
            </div>
            <h2 className="font-semibold text-lg tracking-tight text-white glow-text">
              Global Platform Sentiment
            </h2>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 overflow-hidden flex flex-col relative z-10 px-4 sm:px-10 reflection-mask">
        <div className="max-w-4xl w-full mx-auto overflow-y-auto pt-10 pb-20 h-full scrollbar-hide">
          
          <div className="mb-10">
            <h3 className="serif text-3xl text-white mb-2">Insights & Mood</h3>
            <p className="text-white/50 text-sm">Aggregated, fully anonymized analysis of all platform entries generated by Gemini.</p>
          </div>

          {loading ? (
            <div className="flex justify-center py-20">
              <Loader2 className="w-8 h-8 animate-spin text-violet-400/50" />
            </div>
          ) : error ? (
            <div className="text-center bg-red-500/10 border border-red-500/20 rounded-2xl p-6">
              <p className="text-red-400 text-sm font-medium">{error}</p>
            </div>
          ) : entries.length === 0 ? (
            <div className="text-center py-20 m-auto">
              <div className="w-16 h-16 bg-white/5 border border-white/10 text-white/40 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-sm">
                <BarChart2 className="w-8 h-8" />
              </div>
              <h3 className="text-xl serif text-white/90 mb-2 glow-text">No Analysis Found</h3>
              <p className="text-white/50 max-w-sm mx-auto text-sm">
                The global sentiment cron job has not run yet, or there are no journal entries to analyze.
              </p>
            </div>
          ) : (
            <div className="space-y-8">
              {entries.map((entry) => (
                <div key={entry.id} className="glass rounded-2xl p-6 sm:p-8 border border-white/5 relative overflow-hidden group">
                  <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-violet-500/0 via-violet-500/20 to-violet-500/0 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                  
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
                    <div className="flex items-center gap-2 text-white/40 text-xs font-semibold tracking-wider uppercase">
                      <Calendar className="w-4 h-4" />
                      {formatDate(entry.timestamp)}
                    </div>
                    <div className="flex items-center gap-2 text-xs font-medium text-violet-300 bg-violet-500/10 border border-violet-500/20 px-3 py-1.5 rounded-lg">
                      <BarChart2 className="w-3.5 h-3.5" />
                      Analyzed {entry.entryCount} Entries
                    </div>
                  </div>
                  
                  <div className="prose prose-invert prose-violet max-w-none">
                    <p className="whitespace-pre-wrap leading-relaxed text-white/80 text-[15px]">
                      {entry.analysis}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
